### PR TITLE
Display image using background-image style attribute instead of img tag

### PR DESCRIPTION
**Pull request by calvinlough**

### CODE REVIEW

**Comment by adampetrie** [comment]
Looks good to me

**Comment by AntonNguyen** [comment]
:shipit:

**Comment by skaasten** [comment]
What's rimraf used for?

**Comment by calvinlough** [comment]
It's a dependency of a library that we use I think. They released a buggy version so we need to pin it at the root level to get the version we want. More info here: https://github.com/ember-cli/ember-cli/issues/3486#issuecomment-78039493

**Pull request merged**
