### PR TITLE
Update to ember-cli 0.2.7

### PR DESCRIPTION
**Pull request by mattmcmanus**
I've got another PR coming but couldn't really make any changes until the cli version was updated.

Most of the changes are from running `ember init` after updating. I also installed ember-watson to take care of prototype extensions and the qunit tests. Everything is setup in it's own commit.

### CODE REVIEW

**Comment by f3ndot** [comment]
Thanks for this! Please reinstate the `version`, `description`, etc. in `package.json` and we'll merge it in!

**Comment by mattmcmanus** [comment]
Yikes! Should of caught that. I'd also let another modification in. Everything is tidied up now though.

**Comment by f3ndot** [comment]
Had to retrigger Travis CI :smile:

**Comment by mattmcmanus** [comment]
ember is killing me these days with all the changes. This failing test on ember-beta had to do with an old version of ember qunit (https://github.com/ember-cli/ember-cli/issues/4305)

**Comment by mattmcmanus** [comment]
Hey, the tests are only failing on the beta/canary channel. Do you still want to hold off on merging this?

**Comment by alexBaizeau** [comment]
Thanks a lot!

**Pull request merged**
