### PR TITLE
add {{yield}}

### PR DESCRIPTION
**Pull request by miguelcobain**
The reason to add a `{{yield}}` statement is to allow for better interop with some tooltip components in the wild.

Example in ember-paper:
```hbs
{{#initials-avatar
  firstName=userGivenName
  lastName=userFamilyName
  company=userCompany
  email=userEmail
  image=userProfileImageUrl}}
  {{#paper-tooltip}}
    this text will appear on a tooltip
  {{/paper-tooltip}}
{{/initials-avatar}}
```

or in ember-bootstrap:
```hbs
{{#initials-avatar
  firstName=userGivenName
  lastName=userFamilyName
  company=userCompany
  email=userEmail
  image=userProfileImageUrl}}
  {{#bs-tooltip placement="bottom"}}
    Tooltip on bottom
  {{/bs-tooltip}}
{{/initials-avatar}}
```

This is a non-breaking change to anyone already using this component.

### CODE REVIEW

**Comment by k-fish** [comment]
Looks fine so long as tests pass. 👍

**Comment by miguelcobain** [comment]
Seems like ember beta and canary use `WeakMap`, which isn't available on PhantomJS, hence the errors.

This project should be updated with latest ember-cli and latest testing best practices which use headless Chrome. I can put together a PR with that.

**Comment by miguelcobain** [comment]
Seems like I already did that in the past https://github.com/freshbooks/initials-avatar/pull/19

😄

**Comment by miguelcobain** [comment]
@k-fish after merging https://github.com/freshbooks/initials-avatar/pull/23, the tests should pass.

**Comment by miguelcobain** [comment]
You probably need restart Travis tests.

**Comment by miguelcobain** [comment]
@k-fish any news on this?

If you restart travis tests, they should pass now.

**Comment by k-fish** [comment]
I tried restarting it last week and it errored out, going to give it another shot.

**Comment by miguelcobain** [comment]
@k-fish I probably just needed to rebase against current master, which I just did. Should pass now.

**Comment by k-fish** [comment]
👍

**Comment by miguelcobain** [comment]
@k-fish It's finally passing! Sorry for the trouble.

**Comment by k-fish** [comment]
No worries, thanks for the PR.

**Comment by k-fish** [comment]
Tagged and released. Give it a shot.

**Pull request merged**
